### ISSUE TITLE
Feature req: Template compilation as build step

### ISSUE THREAD

**Issue by Birowsky** [OzTK/elm-view-engine#4]
Thanx for your efforts in this awesome package!

Haven't benchmarked, but I can imagine the templates compilation step being hell of an expensive operation. Instead of compiling in runtime, I'm imagining an ideal scenario where the templates are compiled down to simple functions in build time, and then, in runtime we simply call those functions with the view parameters to get back the full views.

Thoughts?

**Comment by OzTK** [comment]
Thank you for using it :) I definitely need some people to use it so I can have some feedback!

What you are requesting is actually already possible, But I haven't well-documented it yet.

You can call `elm-view-engine` from an npm script and it will compile your views to a js file. If the engine detects that file at the configure step, it will use it instead of recompiling every time.

You can also try `elm-view-engine --help` to learn about the options you can pass it.

I would also advise to upgrade to v2.0 as the template format changed and is clearer (I updated the doc about this ;) )

**Comment by Birowsky** [comment]
Well thank you, mister!
